女性限定イベント機能の実装（事業をエンジニアリングしよう 実装編 の回答）
Misu759/mokumoku pull request #2
Opened 2022-11-27 11:38 UTC by Misu759

事業をエンジニアリングしよう 実装編 の回答です。レビューお願いします。

# 選択した課題

1. サービス登録者数の内、男性60%に対して、女性は40%。一方で、サービス内のもくもく会に参加した人の比率は、男性90%：女性10%と大きな差が出ています。もっと女性が使いやすいようなサービス設計にする必要があるのではないか？

# テスト結果
<img width="942" alt="image" src="https://user-images.githubusercontent.com/71998782/204133159-6f49375c-837e-4f26-8aa8-2f84bf3b494a.png">
<img width="931" alt="image" src="https://user-images.githubusercontent.com/71998782/204133194-a53a4514-547e-4b5d-a9dd-983ac6f6046c.png">

2022-11-28 10:29 UTC, busitora requested changes
コメントしました！

2022-11-28 10:29 UTC, busitora commented on app/views/events/show.html.erb
> +              <% if !@event.only_woman || current_user.woman? %>
if文が冗長になっているので、 処理をmodel等に寄せる等手段をとってみてください！

2022-11-28 11:01 UTC, Misu759 commented
コメントありがとうございます。
該当箇所修正しました。よろしくお願いします。
<img width="962" alt="image" src="https://user-images.githubusercontent.com/71998782/204261772-192b9991-cf69-40fb-a3a6-0ed176d9f146.png">
<img width="907" alt="image" src="https://user-images.githubusercontent.com/71998782/204261826-be2fc53a-84a4-427c-aaa3-77601324c75a.png">

2022-11-28 12:18 UTC, busitora reviewed
いいですね！
if 文がまだ多いですが、 && 等で囲ってネストは減らせるところまで省略してみましょう！

2022-11-28 13:06 UTC, Misu759 commented
ありがとうございます！
ネスト減らしてみました。よろしくお願いします！

<img width="990" alt="image" src="https://user-images.githubusercontent.com/71998782/204284969-ac9382f7-8fa6-4015-bc67-45c8bc620fd3.png">
<img width="918" alt="image" src="https://user-images.githubusercontent.com/71998782/204285058-8417af08-ed0e-46a0-9ef4-c820b9a1e4be.png">

2022-11-29 10:37 UTC, enda1111 approved these changes
1点コメントしましたが、LGTMです！
マージして次の課題に進みましょう。

2022-11-29 10:37 UTC, enda1111 commented on app/models/event.rb
> +    !!user && (!only_woman || user.woman?) && !user.owner?(self)
ruby的には `!!user` ではなく `user` を使ってしまう事が多いですかね。
もしくは rails であれば `user.present?` の方がコードの意図は読みやすいかなと思います！

2022-11-29 12:09 UTC, Misu759 commented
ありがとうございます！勉強になりました。

2022-11-29 12:10 UTC, merged